# image: kradalby/python
image: evonove/ci

git:
  path: github.com/kradalby/aspargesgaarden.no

env:
    - DJANGO_SETTINGS_MODULE=init_django.settings.dev

script:
    - pip install tox
    - tox

notify:
  email:
    recipients:
      - kradalby@kradalby.no

deploy:
  bash:
    script: 
      - 'git -C ~/git/plays pull'
      - 'ansible-playbook -i ~/git/plays/inventory ~/git/plays/deploy/aspargesgaarden.no.yml'
