build:
    image: kradalby/ci-tox:latest
    pull: true
    environment:
      - DJANGO_SETTINGS_MODULE=init_django.settings.dev
    commands:
      - tox

notify:
  email:
    from: drone@fap.no
    host: smtp.stud.ntnu.no
    port: 25
    recipients:
      - kradalby@kradalby.no

publish:
  docker:
    registry: gengar.l.fap.no:5000
    repo: aspargesgaarden/aspargesgaarden
    tag: latest
    insecure: true
    when:
        branch: master
    load: docker/image.tar
    save:
      destination: docker/image.tar
      tag: latest

deploy:
  ssh:
    host:
     - gengar.l.fap.no
    user: root
    port: 22
    sleep: 2
    commands:
      - docker pull registry.fap.no/aspargesgaarden/aspargesgaarden:latest
      - docker-compose -f /srv/docker/aspargesgaarden/docker-compose.yml stop
      - docker-compose -f /srv/docker/aspargesgaarden/docker-compose.yml up -d
    when:
        branch: master
