build:
    image: kradalby/ci-tox:latest
    pull: true
    environment:
      - DJANGO_SETTINGS_MODULE=init_django.settings.dev
    commands:
      - tox

notify:
  email:
    from: drone@fap.no
    host: smtp.stud.ntnu.no
    port: 25
    recipients:
      - kradalby@kradalby.no

deploy:
  ssh:
    host: onyx.fap.no
    user: www
    port: 22
    commands:
      - cd /usr/local/www/aspargesgaarden.no
      - git pull
      - export DJANGO_SETTINGS_MODULE=init_django.settings.prod
      - make prod
      - make migrate
      - supervisorctl restart uwsgi_aspargesgaarden.no
