# image: kradalby/python
image: evonove/ci

git:
  path: github.com/kradalby/aspargesgaarden.no

env:
    - DJANGO_SETTINGS_MODULE=init_django.settings.dev

script:
    - pip install tox
    - tox

notify:
  email:
    recipients:
      - kradalby@kradalby.no

deploy:
  bash:
    script: 
        - 'pip install ansible'
        - 'git clone https://github.com/kradalby/plays.git'
        - 'ansible-playbook -i plays/inventory plays/deploy/aspargesgaarden.no.yml'
