# image: kradalby/python
image: kradalby/ci-tox

git:
  path: github.com/kradalby/aspargesgaarden.no

env:
    - DJANGO_SETTINGS_MODULE=init_django.settings.dev

script:
    - tox

notify:
  email:
    recipients:
      - kradalby@kradalby.no

deploy:
  bash:
    script: 
        - 'git clone https://github.com/kradalby/plays.git'
        - 'ansible-playbook -i plays/inventory plays/deploy/aspargesgaarden.no.yml'
